name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Sync deps (dev)
        working-directory: src
        run: uv sync --extra dev
      - name: Ruff check
        working-directory: src
        run: uv run ruff check app/

  typecheck:
    name: Mypy Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Sync deps (dev)
        working-directory: src
        run: uv sync --extra dev
      - name: Mypy
        working-directory: src
        run: uv run mypy app/
  bicep:
    name: Bicep Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bicep CLI
        run: |
          set -euxo pipefail
          BICEP_VERSION=v0.37.4
          mkdir -p "$HOME/.local/bin"
          curl -L -o "$HOME/.local/bin/bicep" "https://github.com/Azure/bicep/releases/download/${BICEP_VERSION}/bicep-linux-x64"
          chmod +x "$HOME/.local/bin/bicep"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Bicep version
        run: bicep --version
      - name: Restore Bicep modules
        run: bicep restore infra/main.bicep
      - name: Validate Bicep Templates
        run: bicep build infra/main.bicep
